---
apiVersion: v1
kind: Namespace
metadata:
  name: pet-battle-ch
spec:
---
# this channel is used to point to the folders staging and prod for a gitops approach to using helm
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: pet-battle-gitops
  namespace: pet-battle-ch
spec:
  type: GitHub
  pathname: https://github.com/ggoksu/pet-battle.git
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: cat-app
  namespace: pet-battle-ch
spec:
  type: HelmRepo
  pathname: https://dschromeos.github.io/pet-battle/
